language: objective-c
osx_image: xcode9.0
xcode_workspace: VirtualGameController.xcworkspace
xcode_scheme:
- VirtualGameControllerIOS
- VirtualGameControllerOSX
- VirtualGameControllerTvOS
- VirtualGameControllerWatchOS
xcode_sdk:
- iphonesimulator9.2
- macosx10.12
- appletvos10.2
- watchos3.2
matrix:
     exclude:
           - xcode_scheme: VirtualGameControllerIOS
             xcode_sdk: macosx10.12
           - xcode_scheme: VirtualGameControllerIOS
             xcode_sdk: appletvos10.2
           - xcode_scheme: VirtualGameControllerIOS
             xcode_sdk: watchos3.2
           - xcode_scheme: VirtualGameControllerOSX
             xcode_sdk: iphonesimulator9.2
           - xcode_scheme: VirtualGameControllerOSX
             xcode_sdk: appletvos10.2
           - xcode_scheme: VirtualGameControllerOSX
             xcode_sdk: watchos3.2
           - xcode_scheme: VirtualGameControllerTvOS
             xcode_sdk: macosx10.12
           - xcode_scheme: VirtualGameControllerTvOS
             xcode_sdk: appletvos10.2
           - xcode_scheme: VirtualGameControllerTvOS
             xcode_sdk: watchos3.2
           - xcode_scheme: VirtualGameControllerWatchOS
             xcode_sdk: iphonesimulator9.2
           - xcode_scheme: VirtualGameControllerWatchOS
             xcode_sdk: appletvos10.2
           - xcode_scheme: VirtualGameControllerWatchOS
             xcode_sdk: watchos3.2
