language: swift
osx_image: xcode10.1
xcode_workspace: VirtualGameController.xcworkspace
xcode_scheme:
- VirtualGameControllerIOS
- VirtualGameControllerOSX
- VirtualGameControllerTvOS
- VirtualGameControllerWatchOS
xcode_sdk:
- iphonesimulator12.1
- macosx10.14
- appletvos12.1
- watchos5.1
script:
- xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO
matrix:
     exclude:
           - xcode_scheme: VirtualGameControllerIOS
             xcode_sdk: macosx10.14
           - xcode_scheme: VirtualGameControllerIOS
             xcode_sdk: appletvos12.1
           - xcode_scheme: VirtualGameControllerIOS
             xcode_sdk: watchos5.1
           - xcode_scheme: VirtualGameControllerOSX
             xcode_sdk: iphonesimulator12.1
           - xcode_scheme: VirtualGameControllerOSX
             xcode_sdk: appletvos12.1
           - xcode_scheme: VirtualGameControllerOSX
             xcode_sdk: watchos5.1
           - xcode_scheme: VirtualGameControllerTvOS
             xcode_sdk: macosx10.14
           - xcode_scheme: VirtualGameControllerTvOS
             xcode_sdk: appletvos12.1
           - xcode_scheme: VirtualGameControllerTvOS
             xcode_sdk: watchos5.1
           - xcode_scheme: VirtualGameControllerWatchOS
             xcode_sdk: iphonesimulator12.1
           - xcode_scheme: VirtualGameControllerWatchOS
             xcode_sdk: appletvos12.1
           - xcode_scheme: VirtualGameControllerWatchOS
             xcode_sdk: watchos5.1
