language: swift
osx_image: xcode10.1
xcode_workspace: VirtualGameController.xcworkspace
xcode_scheme:
- VirtualGameControllerIOS
- VirtualGameControllerOSX
- VirtualGameControllerTvOS
xcode_sdk:
- iphonesimulator12.1
- macosx10.14
- appletvos12.1
matrix:
    exclude:
        - xcode_scheme: VirtualGameControllerIOS
        xcode_sdk: macosx10.14
        - xcode_scheme: VirtualGameControllerIOS
        xcode_sdk: appletvos12.1
        - xcode_scheme: VirtualGameControllerOSX
        xcode_sdk: iphonesimulator12.1
        - xcode_scheme: VirtualGameControllerOSX
        xcode_sdk: appletvos12.1
        - xcode_scheme: VirtualGameControllerTvOS
        xcode_sdk: macosx10.14
        - xcode_scheme: VirtualGameControllerTvOS
        xcode_sdk: appletvos12.1
        - xcode_scheme: VirtualGameControllerWatchOS 
        xcode_sdk: iphonesimulator12.1
        - xcode_scheme: VirtualGameControllerWatchOS
        xcode_sdk: appletvos12.1
